<?xml version="1.0" encoding="utf-8"?><Database Name="StationaryDB" Class="StationaryDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\StationaryDB.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="StationaryDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Item" Member="Items">
    <Type Name="Item">
      <Column Name="ItemCode" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ItemCost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ItemQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Item_Application" Member="Applications" ThisKey="ItemCode" OtherKey="ItemCode" Type="Application" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Designation" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Employee_Application" Member="Applications" ThisKey="EmployeeID" OtherKey="emyID" Type="Application" />
      <Association Name="Employee_Application1" Member="Applications1" ThisKey="EmployeeID" OtherKey="emyID" Type="Application" />
    </Type>
  </Table>
  <Table Name="dbo.Applications" Member="Applications">
    <Type Name="Application">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemCode" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Itemqty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="superiorId" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ApproveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="emyID" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Remarks" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Employee_Application" Member="Employee" ThisKey="emyID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
      <Association Name="Employee_Application1" Member="Employee1" ThisKey="emyID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Item_Application" Member="Item" ThisKey="ItemCode" OtherKey="ItemCode" Type="Item" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>